export const OPTIONSCOUNTRY = [
	{value: "", label: "Seleccione un país"},
	{value: "AR", label: "Argentina"},
	{value: "BO", label: "Bolivia"},
	{value: "BR", label: "Brazil"},
	{value: "CL", label: "Chile"},
	{value: "CO", label: "Colombia"},
	{value: "CR", label: "Costa Rica"},
	{value: "CU", label: "Cuba"},
	{value: "EC", label: "Ecuador"},
	{value: "SV", label: "El Salvador"},
	{value: "ES", label: "España"},
	{value: "US", label: "Estados Unidos"},
	{value: "GT", label: "Guatemala"},
	{value: "HN", label: "Honduras"},
	{value: "MX", label: "México"},
	{value: "NI", label: "Nicaragua"},
	{value: "PA", label: "Panamá"},
	{value: "PY", label: "Paraguay"},
	{value: "PE", label: "Perú"},
	{value: "PR", label: "Puerto Rico"},
	{value: "DO", label: "República Dominicana"},
	{value: "UY", label: "Uruguay"},
	{value: "VE", label: "Venezuela"},
];
